# Generated by Django 4.2.11 on 2024-03-12 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RangerApp', '0002_category_ranger_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prix', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('User', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('prix', models.PositiveIntegerField()),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('Service', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='RangerApp.service')),
            ],
        ),
    ]
