# Generated by Django 4.2.11 on 2024-03-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RangerApp', '0003_service_salary_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranger',
            old_name='Category',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='author',
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='year',
        ),
        migrations.AddField(
            model_name='ranger',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
