# Generated by Django 4.2.11 on 2024-03-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RangerApp', '0008_remove_user_is_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=False),
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='category',
        ),
        migrations.AddField(
            model_name='ranger',
            name='category',
            field=models.ManyToManyField(to='RangerApp.category'),
        ),
    ]
