# Generated by Django 4.2.11 on 2024-03-16 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RangerApp', '0009_category_slug_remove_ranger_category_ranger_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ranger',
            name='category',
        ),
        migrations.AddField(
            model_name='ranger',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='RangerApp.category'),
        ),
    ]
