# Generated by Django 4.2.11 on 2024-03-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RangerApp', '0010_remove_category_slug_remove_ranger_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranger',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='cname',
            new_name='name',
        ),
    ]
